---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: {{ .Release.Namespace }}
  name: mem-limit-mendhak
spec:
  limits:
  - default:
      cpu:    {{ .Values.container.cpu }}
      memory: {{ .Values.container.memory }}
    defaultRequest:
      cpu:    {{ .Values.container.cpurequest }}
      memory: {{ .Values.container.memoryrequest }}
    type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: deployment-mendhak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-mendhak
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-mendhak
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: app-mendhak
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: ingress-mendhak
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-mendhak
              port:
                number: 80
